from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
path = ROOT / "bot.py"
text = path.read_text(encoding="utf-8")

startup_old = '''    conn = sqlite3.connect(db_path, timeout=15)\n    conn.row_factory = sqlite3.Row\n\n    try:\n        rows = conn.execute(\n'''
startup_new = '''    conn = sqlite3.connect(db_path, timeout=15)\n    conn.row_factory = sqlite3.Row\n\n    try:\n        # Canonical Web state wins over legacy bot.db claim rows.  Final Web\n        # orders must never keep a live/recoverable DispatchClaimView record.\n        final_rows = conn.execute(\n            """\n            SELECT dispatch_message_id\n            FROM web_orders\n            WHERE status IN ('closed', 'cancelled')\n              AND dispatch_message_id IS NOT NULL\n              AND TRIM(dispatch_message_id) <> ''\n            """\n        ).fetchall()\n\n        removed_final_claims = 0\n        for final_row in final_rows:\n            final_message_id = _to_int(final_row["dispatch_message_id"], None)\n            if final_message_id is None:\n                continue\n\n            if final_message_id in ORDER_CLAIMS:\n                ORDER_CLAIMS.pop(final_message_id, None)\n                removed_final_claims += 1\n\n            delete_claim_row_from_db(message_id=final_message_id)\n\n        if removed_final_claims:\n            print(\n                f"[claims] startup removed final Web-order claims: "\n                f"{removed_final_claims}",\n                flush=True,\n            )\n\n        rows = conn.execute(\n'''
if startup_old not in text:
    raise SystemExit("startup reconcile insertion point not found")
text = text.replace(startup_old, startup_new, 1)

process_old = '''async def _process_existing_web_sync_event(event: dict) -> None:\n    event_id = int(event["event_id"])\n    retry_count = int(event.get("retry_count") or 0)\n\n    try:\n        await _refresh_existing_web_sync_dispatch(event)\n        _web_sync_mark_event_done(event_id)\n        print(f"[web-sync] event_id={event_id} done order_id={event.get('order_id')}")\n    except Exception as exc:\n        _web_sync_mark_event_failed(event_id, str(exc), retry_count)\n        print(f"處理網站同步事件失敗 event_id={event_id}：{exc}")\n'''
process_new = '''async def _process_existing_web_sync_event(event: dict) -> None:\n    event_id = int(event["event_id"])\n    retry_count = int(event.get("retry_count") or 0)\n\n    try:\n        order_id = _to_int(event.get("order_id"), None)\n\n        # A generic order_updated event can arrive after the Web order is final.\n        # Do not rebuild/persist a claim for a closed/cancelled order; instead\n        # reconcile the legacy Bot claim row to the canonical Web state.\n        if order_id is not None:\n            conn = sqlite3.connect(_web_dashboard_db_path_for_bot(), timeout=15)\n            try:\n                final_row = conn.execute(\n                    """\n                    SELECT status, dispatch_message_id\n                    FROM web_orders\n                    WHERE id = ?\n                    LIMIT 1\n                    """,\n                    (int(order_id),),\n                ).fetchone()\n            finally:\n                conn.close()\n\n            if final_row is not None and str(final_row[0] or "").strip().lower() in {"closed", "cancelled"}:\n                final_message_id = _to_int(final_row[1], None)\n                if final_message_id is not None:\n                    ORDER_CLAIMS.pop(final_message_id, None)\n                    delete_claim_row_from_db(message_id=final_message_id)\n\n                _web_sync_mark_event_done(event_id)\n                print(\n                    f"[web-sync] event_id={event_id} final-order claim cleaned "\n                    f"order_id={order_id}",\n                    flush=True,\n                )\n                return\n\n        await _refresh_existing_web_sync_dispatch(event)\n        _web_sync_mark_event_done(event_id)\n        print(f"[web-sync] event_id={event_id} done order_id={event.get('order_id')}")\n    except Exception as exc:\n        _web_sync_mark_event_failed(event_id, str(exc), retry_count)\n        print(f"處理網站同步事件失敗 event_id={event_id}：{exc}")\n'''
if process_old not in text:
    raise SystemExit("existing web sync event target not found")
text = text.replace(process_old, process_new, 1)

path.write_text(text, encoding="utf-8")
